version: '3.8'

services:
  user-frontend:
    build:
      context: ./user-frontend
      dockerfile: ../Dockerfile.user
    ports:
      - "80:80"
    depends_on:
      - server
    restart: unless-stopped

  admin-frontend:
    build:
      context: ./admin-frontend
      dockerfile: ../Dockerfile.admin
    ports:
      - "81:80"
    depends_on:
      - server
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: ../Dockerfile.server
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
    restart: unless-stopped 